// Small, explicitly labeled sample catalog. Real search uses TMDB when configured.
export const genres = [
  { id: 28, name: 'แอ็กชัน' },
  { id: 12, name: 'ผจญภัย' },
  { id: 16, name: 'แอนิเมชัน' },
  { id: 35, name: 'ตลก' },
  { id: 80, name: 'อาชญากรรม' },
  { id: 18, name: 'ดราม่า' },
  { id: 14, name: 'แฟนตาซี' },
  { id: 27, name: 'สยองขวัญ' },
  { id: 10749, name: 'โรแมนติก' },
  { id: 878, name: 'ไซไฟ' },
  { id: 53, name: 'ระทึกขวัญ' },
]
const rows = [
  [
    157336,
    'Interstellar',
    '2014',
    8.4,
    [878, 18, 12],
    '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    169,
    'เมื่อโลกไม่ใช่บ้านที่ปลอดภัยอีกต่อไป อดีตนักบินจึงออกเดินทางข้ามจักรวาลเพื่อค้นหาบ้านใหม่ให้มนุษยชาติ ท่ามกลางระยะทางที่ทดสอบความผูกพันระหว่างพ่อกับลูก',
  ],
  [
    693134,
    'Dune: Part Two',
    '2024',
    8.1,
    [878, 12],
    '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    '/xOMo8BRK7PfcJv72hQnUjvBnI5O.jpg',
    167,
    'พอล อะเทรดีส ร่วมเดินทางกับชาวเฟรเมนบนดาวทะเลทราย และต้องเลือกระหว่างความรักกับชะตากรรมของจักรวาล',
  ],
  [
    27205,
    'Inception',
    '2010',
    8.4,
    [28, 878, 12],
    '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    148,
    'ทีมผู้เชี่ยวชาญการแทรกซึมความฝันได้รับภารกิจปลูกความคิดลงในจิตใจ เปลี่ยนการโจรกรรมให้เป็นการเดินทางผ่านโลกหลายชั้น',
  ],
  [
    129,
    'Spirited Away',
    '2001',
    8.5,
    [16, 14, 12],
    '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    null,
    125,
    'เด็กหญิงหลงเข้าสู่โลกวิญญาณ และเรียนรู้ความกล้าหาญระหว่างพยายามช่วยพ่อแม่และหาทางกลับบ้าน',
  ],
  [
    105,
    'Back to the Future',
    '1985',
    8.3,
    [12, 35, 878],
    '/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg',
    null,
    116,
    'การเดินทางย้อนเวลาโดยบังเอิญทำให้เด็กหนุ่มต้องจับคู่พ่อแม่ในวัยเรียน เพื่อรักษาอนาคตของตัวเอง',
  ],
  [
    313369,
    'La La Land',
    '2016',
    7.9,
    [35, 18, 10749],
    '/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
    null,
    128,
    'นักดนตรีแจ๊สและนักแสดงสาวต่างไล่ตามความฝันในลอสแอนเจลิส พร้อมเรียนรู้ว่าความรักและความสำเร็จอาจเดินคนละทาง',
  ],
  [
    238,
    'The Godfather',
    '1972',
    8.7,
    [18, 80],
    '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    null,
    175,
    'ทายาทที่เคยหลีกหนีธุรกิจครอบครัวค่อย ๆ ถูกดึงเข้าสู่โลกแห่งอำนาจ ความภักดี และการตัดสินใจที่เปลี่ยนชีวิต',
  ],
  [
    550,
    'Fight Club',
    '1999',
    8.4,
    [18, 53],
    '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    null,
    139,
    'ชายผู้เหนื่อยหน่ายชีวิตพบคนแปลกหน้าที่พาเขาไปตั้งชมรมลับ ซึ่งเติบโตเกินกว่าที่ใครจะควบคุมได้',
  ],
  [
    496243,
    'Parasite',
    '2019',
    8.5,
    [35, 53, 18],
    '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    null,
    132,
    'ครอบครัวหนึ่งค่อย ๆ เข้าไปทำงานในบ้านคนร่ำรวย ความลับและความเหลื่อมล้ำทำให้เรื่องราวพลิกผัน',
  ],
  [
    155,
    'The Dark Knight',
    '2008',
    8.5,
    [28, 80, 18],
    '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    null,
    152,
    'แบทแมนเผชิญผู้ร้ายที่ใช้ความโกลาหลทดสอบเส้นแบ่งระหว่างความยุติธรรมกับการเสียสละ',
  ],
  [
    10681,
    'WALL·E',
    '2008',
    8.1,
    [16, 878, 12],
    '/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg',
    null,
    98,
    'หุ่นยนต์เก็บขยะตัวสุดท้ายบนโลกพบแขกจากอวกาศ และออกเดินทางเล็ก ๆ ที่อาจเปลี่ยนอนาคตมนุษยชาติ',
  ],
  [
    120,
    'The Fellowship of the Ring',
    '2001',
    8.4,
    [12, 14],
    '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    null,
    178,
    'ฮอบบิทหนุ่มและเหล่าสหายออกเดินทางเพื่อทำลายแหวนทรงอำนาจ ก่อนความมืดจะครอบงำมิดเดิลเอิร์ธ',
  ],
]
export const demoMovies = rows.map(
  ([
    id,
    title,
    year,
    vote_average,
    genre_ids,
    poster_path,
    backdrop_path,
    runtime,
    overview,
  ]) => ({
    id,
    title,
    original_title: title,
    release_date: year + '-01-01',
    vote_average,
    genre_ids,
    poster_path,
    backdrop_path,
    runtime,
    overview,
    genres: genres.filter((genre) => genre_ids.includes(genre.id)),
    credits: { cast: [], crew: [] },
    videos: { results: [] },
  }),
)
